## Regression

In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
df= pd.read_csv("/content/calories.csv")
df.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [13]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.1.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.26.4)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost) (2.23.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.13.1)

In [14]:
df.shape

(15000, 2)

In [15]:
df.isnull().sum()

User_ID     0
Calories    0
dtype: int64

In [16]:
df_data= pd.read_csv("/content/exercise.csv")
df_data.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [17]:
df= pd.concat([df,df_data],axis=1)
df.head()

,User_ID,Calories,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp
0,14733363,231.0,14733363,male,68,190.0,94.0,29.0,105.0,40.8
1,14861698,66.0,14861698,female,20,166.0,60.0,14.0,94.0,40.3
2,11179863,26.0,11179863,male,69,179.0,79.0,5.0,88.0,38.7
3,16180408,71.0,16180408,female,34,179.0,71.0,13.0,100.0,40.5
4,17771927,35.0,17771927,female,27,154.0,58.0,10.0,81.0,39.8

In [21]:
df.drop(columns=["User_ID"],axis=1,inplace=True)

In [22]:
df.head()

   Calories  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0     231.0    male   68   190.0    94.0      29.0       105.0       40.8
1      66.0  female   20   166.0    60.0      14.0        94.0       40.3
2      26.0    male   69   179.0    79.0       5.0        88.0       38.7
3      71.0  female   34   179.0    71.0      13.0       100.0       40.5
4      35.0  female   27   154.0    58.0      10.0        81.0       39.8

In [23]:
df.shape

(15000, 8)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Calories    15000 non-null  float64
 1   Gender      15000 non-null  object
 2   Age         15000 non-null  int64
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 937.6+ KB

In [25]:
df.isnull().sum()

Calories      0
Gender        0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
dtype: int64

In [26]:
df["Gender"].value_counts()

Gender
female    7553
male      7447
Name: count, dtype: int64

In [27]:
df["Gender"]= df["Gender"].apply(lambda x:1 if x=="male" else 0)

In [28]:
df["Gender"].value_counts()

Gender
0    7553
1    7447
Name: count, dtype: int64

In [29]:
df.head()

   Calories  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0     231.0       1   68   190.0    94.0      29.0       105.0       40.8
1      66.0       0   20   166.0    60.0      14.0        94.0       40.3
2      26.0       1   69   179.0    79.0       5.0        88.0       38.7
3      71.0       0   34   179.0    71.0      13.0       100.0       40.5
4      35.0       0   27   154.0    58.0      10.0        81.0       39.8

In [35]:
X=df.iloc[:,1:]

In [33]:
y=df.iloc[:,:1]

In [34]:
y

       Calories
0         231.0
1          66.0
2          26.0
3          71.0
4          35.0
...         ...
14995      45.0
14996      23.0
14997      75.0
14998      11.0
14999      98.0

[15000 rows x 1 columns]

In [36]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.20,random_state=7)
print(X_train.shape, X_test.shape, y_train.shape,y_test.shape)

(12000, 7) (3000, 7) (12000, 1) (3000, 1)

In [37]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [38]:
from xgboost import XGBRegressor
model= XGBRegressor()

model.fit(X_train,y_train)

y_pred= model.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error

print(f"R2 score: {r2_score(y_test,y_pred)}")
print(f"MAE: {mean_absolute_error(y_test,y_pred)}")

R2 score: 0.9987369179725647
MAE: 1.4904924735625584

In [40]:
input_data= [0,24,165.0,59.0,18.0,91.0,40.2]
input_data_array= np.asarray(input_data).reshape(1,-1)

data_scaled = scaler.transform(input_data_array)
prediction= model.predict(data_scaled)

print(f"Calories burnt : {prediction[0]}")

Calories burnt : 81.25054931640625

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(